### ISSUE TITLE
very high delays

### ISSUE THREAD

**Issue by Nuikita** [JoseGamerPT/RealScoreboard#1]
![Captura de pantalla (485)](https://user-images.githubusercontent.com/29359652/93166683-9de18380-f6e4-11ea-8774-6af80996f46c.png)

RealScoreboard v13-9-2020 Build 2Total: 351.63 s Pct: 40.27%
   Pct Total	Pct Tick	   Total	      Avg	 PerTick	     Count		Event
      40.26%	  40.03%	351.59 s	    20.02 ms	 8.4	     147.5k	    Task: SBPlayer$1(interval 10)
       0.00%	   0.07%	  0.03 s	     0.03 ms	 0.0	       0.9k	    Task: AnimationManager$1(interval 20)
       0.00%	   0.01%	  0.01 s	     0.01 ms	 0.1	       1.8k	    Task: AnimationManager$2(interval 10)
       0.00%	   0.06%	  0.00 s	     0.03 ms	 0.0	       0.0k	    Task: PlayerManager$1(Single)

**Comment by beniihd3r32tf324g3** [comment]
Since you won't get any answers here anyway, I'll do that briefly.

Set in the config that the scoreboard is not updated every few milliseconds but every 3 or 5 seconds (as you want). Then the lags should be gone.
