### ISSUE TITLE
First Line missing

### ISSUE THREAD

**Issue by thomaboehi** [JoseGamerPT/RealScoreboard#13]
Hello. 

My first line is missing on the scoreboard, sometimes it appears, sometimes it disappear.

This is the code:

        - '&7 '
        - '&6Banque: &7%cmi_user_balance_formated%'
        - '&2Poche: &7%checkitem_amount_mat:gold_ingot% &7Golds'
        - '&7 '
        - '&aExp: &7Niveau %player_level%'
        - ''
        - '&eRang: &b%cmi_user_rank%'
        - '&r'
        - '&8&o/sb toggle'

**Comment by JoseGamerPT** [comment]
Hi there!
Try using %blank% to get a clear line.
