### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by Mariopg03** [JoseGamerPT/RealScoreboard#14]
Hello, i'm Mario and i'm creating a scoreboard using RealScoreboard, but i don't know how can i create a visual effect on a one of the scoreboard lines, changing the text, i wanna put the server discord, webpage, shop, etc.

How can i do that ? I don't know create this option, i know others scoreboards plugins with this option, but i like RealScoreboard, i don't want use another plugin.

Thanks, greetings.

**Comment by Mariopg03** [comment]
I mean, the text line is changing, showing all the information i want to put at intervals of various seconds.

**Comment by JoseGamerPT** [comment]
You can add spaces for timing it.
