### ISSUE TITLE
Trying to Update Teams before its been Sent to player

### ISSUE THREAD

**Issue by LegendaryBob13** [JoseGamerPT/RealScoreboard#15]
Hello! I got an error message while using geyser. https://pastebin.com/Es405icJ 
If you could look into this it would be great because I love this plugin!
I beleive that this is a harmless bug but I hate that it spams the console. 
Thanks!

**Comment by JoseGamerPT** [comment]
Hi there. Any more plugins that manage scoreboard stuff can cause conflict.
