### ISSUE TITLE
/trigger fails to execute

### ISSUE THREAD

**Issue by osc1997** [JoseGamerPT/RealScoreboard#16]
**Server Version:** Paper 1.15.2

**Plugin Version:** 11-4-2020 Build 1

**Description:**
When you trigger an objective it says "You cannot trigger this objective yet" when you should be able to trigger it. And if you remove the RealScoreboard plugin and restart the server then it works as it normally would.

**Recreating the issue:**
1. Create a scoreboard objective with the "trigger" criteria.
(e.g. /minecraft:scoreboard objectives add test trigger)
2. Enable all players to trigger it.
(e.g. /minecraft:scoreboard players enable @a test)
3. Trigger the objective and it should normally just increment the objective for the player executing the command by 1. Instead it says "You cannot trigger this objective yet".
(e.g. /trigger test)

Keep in mind that after a player successfully triggers an objective, they have to be re-enabled to trigger that objective again.
Thanks!

**Comment by JoseGamerPT** [comment]
Hi there.
I don't support Paper servers, only Spigot.
