### ISSUE TITLE
enderpearl

### ISSUE THREAD

**Issue by alex023312** [JoseGamerPT/RealScoreboard#18]
when i throw an enderpearl my server lag and send alot of error msgs in console (server version paperspigot 1.8.8)
![Screenshot (91)](https://user-images.githubusercontent.com/66558845/83969883-29c06400-a8db-11ea-9c73-253a1db4f663.png)

**Comment by alex023312** [comment]
i found what is the problem if i remove this plugin EPearlCooldown the problem is fixing but can you do something about that?

**Comment by JoseGamerPT** [comment]
What version of RealScoreboard are you using?

**Comment by alex023312** [comment]
> What version of RealScoreboard are you using?

25-12-2019 Build 1 you can see it in the picture

**Comment by JoseGamerPT** [comment]
Please try the latest version
