### ISSUE TITLE
Placeholders are missing

### ISSUE THREAD

**Issue by meanly** [JoseGamerPT/RealScoreboard#22]
![2020-07-08_15 05 30](https://user-images.githubusercontent.com/63057881/86888573-f87ec200-c12c-11ea-9ec1-c00547125000.png)

I'm using the latest version
Server Version: 1.15
Config: https://paste.helpch.at/ujonesujef.bash

**Comment by JoseGamerPT** [comment]
maybe your location is too far for the scoreboard to display.
Try using %loc%

**Comment by meanly** [comment]
how about time, playtime and group placeholders? It displays nothing

**Comment by JoseGamerPT** [comment]
can you show me the result?

**Comment by meanly** [comment]
check the picture

**Comment by meanly** [comment]
Updates please?

**Comment by JoseGamerPT** [comment]
I saw the picture, but it forms for me on my testing. Do you have all the dependencies?

**Comment by meanly** [comment]
I have vault and realscoreboard.

**Comment by JoseGamerPT** [comment]
thats weird. it works for me.
