### ISSUE TITLE
Please delete the new PlayerData function in config.yml , this is crazy in logs, TPS drops. 

### ISSUE THREAD

**Issue by iLiDanMoon** [JoseGamerPT/RealScoreboard#23]
![image](https://user-images.githubusercontent.com/65850104/87522055-d4bbfe80-c68d-11ea-96d5-d7a8627338f5.png)

**Comment by iLiDanMoon** [comment]
Config:
  Prefix: '&bТаблица &7| &r'
  Reloaded: '&fThe config has been &areloaded&f.'
  Messages:
    Scoreboard-Toggle:
      'ON': '&fТаблица &aВключена&f.'
      'OFF': '&fТаблица &cВыключена&f.'
  Animations:
    Rainbow-Delay: 10
    Title-Delay: 2
    Scroll-Text:
      Size: 12
      Space: 2
  Scoreboard-Refresh: 2
  Disabled-Worlds:
  - testWorld
  - ExampleWorld2  
  Scoreboard:
    world:
      Lines:
      - '%blank%'
      - ' &7Ник: &b%playername% &8| &b%ping%'
      - ' &7Локация:'
      - ' &bX %x% Y %y% Z %z%'
      - ' &7Работа: &b%jobsr_user_jobs%'
      - ' &7Деньги: &b%money% &8| &7Опыт: &b%xp%'
      - ' &7Онлайн: &b%online%&f/&b%maxplayers%'
      - ' &b%day% &8| &b%time%'
      - ' %rainbow%┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅'
      - ' &7Меню &8| &7Донат:'
      - ' &d/menu &8| &d/donate'
      - ' &7Отключить Таблицу:'
      - ' &c/rsb toggle'
      Title:
      - '%rainbow%✦Таблица✦'
    test:
      Lines:
      - '%blank%'
      - ' &7Hello, &f%playername%'
      - ' &fWelcome to the server!'
      - '%blank%'
      - ' &fYou are on: #&f%world%#'
      - '%blank%'
      Title:
      - '&aFlat &bWorld'
    world3:
      Lines:
      - '&8%rainbow%&l&m------------------------'
      - '&7Third scoreboard'
      - '%rainbow%&l&m------------------------'
      Title:
      - '&6This is the Third scoreboard.'
Version: 3
PlayerData:
  MegaaDiana:
    Scoreboard:
      Status:
        'ON': true
  xX_Vlazhnii_Xx:
    Scoreboard:
      Status:
        'ON': true
  Paxan1234:
    Scoreboard:
      Status:
        'ON': true

**Comment by iLiDanMoon** [comment]
Delete function PlayerData pleas 
![image](https://user-images.githubusercontent.com/65850104/87582444-10cd7e80-c6e3-11ea-8155-3dd34801ffe3.png)

**Comment by JoseGamerPT** [comment]
Fixed. Please use the latest release.
