### ISSUE TITLE
Server load, TPS loss ,can you fix this problem? 1.16.1 15-7-2020 Build 1

### ISSUE THREAD

**Issue by iLiDanMoon** [JoseGamerPT/RealScoreboard#24]
![image](https://user-images.githubusercontent.com/65850104/87857447-5bdbd180-c92f-11ea-82c6-48da430b3d8e.png)
![image](https://user-images.githubusercontent.com/65850104/87857448-61d1b280-c92f-11ea-847d-d9e98f7296ad.png)
![image](https://user-images.githubusercontent.com/65850104/87857450-66966680-c92f-11ea-9792-14b06676f761.png)

**Comment by iLiDanMoon** [comment]
https://timings.aikar.co/?id=a7f8cb18323045db9b4716fb6b4891de

**Comment by iLiDanMoon** [comment]
https://timings.aikar.co/?id=164937f476d14d498c2471b1b6290a6c#timings

**Comment by JoseGamerPT** [comment]
Change the scoreboard refresh rate to reduce lag.

**Comment by iLiDanMoon** [comment]
@JoseGamerPT 
**How much to change ?** 
 Animations:
    Rainbow-Delay: 10
    Title-Delay: 2
    Scroll-Text:
      Size: 12
      Space: 2
  Scoreboard-Refresh: 2
      - '%blank%'
      - ' &7Ник: &b%playername% &8| &b%ping%'
      - ' &7Локация:'
      - ' &bX %x% Y %y% Z %z%'
      - ' &7Работа: &b%jobsr_user_jobs%'
      - ' &7Денег: &b%money% &8| &7Опыт: &b%xp%'
      - ' &7Онлайн: &b%online%&f/&b%maxplayers%'
      - ' &b%day% &8| &b%time%'
      - ' %rainbow%┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅'
      - ' &7Меню &8| &7Донат:'
      - ' &d/menu &8| &d/donate'
      - ' &7Отключить Таблицу:'
      - ' &c/rsb toggle'
      Title:
      - '%rainbow%✦ScoreBoard✦'

**Comment by JoseGamerPT** [comment]
Well it comes to your preference.
The scoreboard refresh comes in ticks, so change it as you need!

**Comment by iLiDanMoon** [comment]
@JoseGamerPT Well, thank you for explaining.
