### ISSUE TITLE
My RealScoreBoard say no API

### ISSUE THREAD

**Issue by MxMasterX** [JoseGamerPT/RealScoreboard#4]
Hello My RealScoreBoard say no API, 
plz can you help me 
here is a code:
[Server thread/WARN]: Plugin RealScoreboard v8-2-2020 Build 1 does not specify an api-version.

**Comment by JoseGamerPT** [comment]
@MxMasterX Hi there!
Can you give me some details about the server?

**Comment by MxMasterX** [comment]
@JoseGamerPT 
Oh sorry, ^^ i use:   PaperMc 1.14.4 at V-Server.

**Comment by MxMasterX** [comment]
Can you help me about api

**Comment by JoseGamerPT** [comment]
Does this happen on Spigot?
