### ISSUE TITLE
%life% Placeholder does not work.

### ISSUE THREAD

**Issue by KrazyKatt1** [JoseGamerPT/RealScoreboard#5]
Hi, I've been using the %life% placeholder that is listed as an available one on your website but it does not function and is only recognised as %life% and stays that way. Please help!

**Comment by JoseGamerPT** [comment]
Hi there please try this version (you have to extract the .jar)
[RealScoreboard.zip](https://github.com/JoseGamerPT/RealScoreboard/files/5503349/RealScoreboard.zip)
