### ISSUE TITLE
Problem with RealScoreboard

### ISSUE THREAD

**Issue by Darkowy** [JoseGamerPT/RealScoreboard#6]
Welcome!
I have a problem with RealScoreboard because it sends the following errors: https://pastebin.pl/view/18bf2f08

**Comment by JoseGamerPT** [comment]
Hi there! Can you send me your config file? Thanks

**Comment by Darkowy** [comment]
https://pastebin.pl/view/1001f5ea

**Comment by JoseGamerPT** [comment]
Your config is missing the Disabled Worlds section, as can be seen here:
https://github.com/JoseGamerPT/RealScoreboard/blob/master/src/main/resources/config.yml

**Comment by joex92** [comment]
> Your config is missing the Disabled Worlds section, as can be seen here:
> https://github.com/JoseGamerPT/RealScoreboard/blob/master/src/main/resources/config.yml

@JoseGamerPT does that means that the `Disabled Worlds` section MUST be set and can't be left empty?

**Comment by JoseGamerPT** [comment]
yes, because if its not set, the plugin will try to find it and it will throw an error if it doesnt.

**Comment by joex92** [comment]
oh well... that explains a lot... 😅
