### ISSUE TITLE
help with the money

### ISSUE THREAD

**Issue by vspres** [JoseGamerPT/RealScoreboard#6]
I have a problem. I use plugins in version 1.15.2 and I have no experience with plugins you can explain to me how to add money

**Comment by JoseGamerPT** [comment]
Hi there.
To add money, you have to use a economy plugin, like vault.
/eco give Player Money

**Comment by vspres** [comment]
Can you please add a link to the plugin? and thank you very much

**Comment by vspres** [comment]
And when I download the vault it doesn't show me the realscoreboard

**Comment by JoseGamerPT** [comment]
What do you mean by don't showing up?

**Comment by vspres** [comment]
![Inked2020-04-01_15 54 04_LI](https://user-images.githubusercontent.com/62903664/78139524-58304780-7431-11ea-9514-fee27e14ac77.jpg)
When I have both plugins, the realiscoreboard doesn't work
