### ISSUE TITLE
Vault plugin shuting down RealScoreBoard

### ISSUE THREAD

**Issue by LANCER245** [JoseGamerPT/RealScoreboard#7]
When i install a (MC version 1.5.12) Vault version 1.7.9 `https://www.spigotmc.org/resources/vault.34315/` the scorboard has stop showing my cofigurated staff. I sent you a pictures before and after. When i uinstall the plugin scoreboard has again show my configurated staff.

After, installing Vault

![image](https://user-images.githubusercontent.com/7526450/79030576-f93da180-7b99-11ea-9e51-12ba1f8b7383.png)

When i uinstall it

![image](https://user-images.githubusercontent.com/7526450/79030562-d7dcb580-7b99-11ea-8d08-50c29450a1d1.png)

I don´t no if this is a your plugin side or i mising some more plugin´s.

Thank´s for answer

**Comment by JoseGamerPT** [comment]
Hi there
Can you send me your config file?
Are there any errors on the console?

**Comment by LANCER245** [comment]
ya i can.

Here is a config.
https://www.dropbox.com/s/88gicf6ukbbjao0/config.yml?dl=0

Here is a server log.
https://pastebin.com/WPLDtM2B

And i do no wot my co-manager done, i test now and plugin is normal working witch **Vault**. And in console plugin loaded without any problem´s and error´s. Im yesterday siting on it 3,5h and another day it´s working. I don't know what the problem was, but now it goes but I want to know what it caused that it stopped working.

Thank´s for your time.
