### ISSUE TITLE
Generating Exceptions 

### ISSUE THREAD

**Issue by ToasterBath2** [JoseGamerPT/RealScoreboard#8]
```
 [Wed, 15. Apr 2020 14:31:22 CDT WARN] Task #9 for RealScoreboard v11-4-2020 Build 1 generated an exception
[Wed, 15. Apr 2020 14:31:22 CDT WARN] Task #81 for RealScoreboard v11-4-2020 Build 1 generated an exception 
```

**My code:**
[(https://pastebin.com/DTLFHZZV)]

**Server Info:**
1.15.2
Plugins: Essentials, Vault, Plugman, RealScoreboard, Supervanish, GriefPrevention

**Comment by JoseGamerPT** [comment]
Hi there, could you send the full log?
Thanks

**Comment by ToasterBath2** [comment]
> Hi there, could you send the full log?
> Thanks

It's just spamming that over and over again, we fixed it. The owner did not paste in the full code I had gave him.
