### ISSUE TITLE
please add option disable warning

### ISSUE THREAD

**Issue by xXjojojXx** [JoseGamerPT/RealScoreboard#8]
please add option disable warning or help in setting war permanent warnings

https://hastebin.com/xobejizaqe.md <------warnings

https://hastebin.com/yocubogoxo.less <-------config

**Comment by JoseGamerPT** [comment]
Hi there
It seems that your config file is broken. Please refer to the default one.

**Comment by xXjojojXx** [comment]
Can you help me?


      - '&6=========================='
      - '&6=&b&lName: &a%playername% &8|&e%ping%&6='
      - '&6=&e%day% &8| &e%time%'
      - '&&6=========================='
      - '&6=&b&lBargeld: &e%money%'
      - '&6=&b&lBank: &e%lighteconomy_player_bank_balance%'
      - '&6=========================='
      - '&6=&b&lBeruf: &e%jobsr_name_(jname/number)%'
      - '&6=&b&lJoblevel: &e%jobsr_maxlvl_(jname/number)%'
      - '&6=&b&lWelt: &e%world%'
      - '&6=========================='
