### ISSUE TITLE
Scoreboard Size

### ISSUE THREAD

**Issue by NeonWeb** [JoseGamerPT/RealScoreboard#9]
The scoreboard is so small on 1.15.2, smaller than it should be.

![image](https://user-images.githubusercontent.com/41237443/79472449-dcf29800-7fd1-11ea-9adb-c633cc4ed3f2.png)

**Comment by JoseGamerPT** [comment]
Hello
The scoreboard has to be smaller in order to support multiple versions.
That's why i included the scrolling feature.
You can also move half of the text to the line below it.
